plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Style/NumericPredicate:
  Exclude:
    - lib/unique_permutation.rb

RSpec/DescribedClass: # Monkey-patching Array — not testing Array itself
  Enabled: false

RSpec/SpecFilePathFormat: # Monkey-patching Array — not testing Array itself
  Enabled: false
